version: '3.7'
services:
  db:
    image: killbill/mariadb:0.24
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
    ports:
      - "3306:3306"

  killbill:
    image: killbill/killbill:0.24.15
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=killbill
      - KILLBILL_DAO_PASSWORD=killbill

  kaui:
    image: killbill/kaui:3.0.10
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=killbill
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080

